### ISSUE TITLE
你好问下，抽取txt文件，一条数据是一个完整的文档吗

### ISSUE THREAD

**Issue by wandouguo** [FreedomIntelligence/Apollo#2]
有没有存在多条数据才是一个完整的文档呢

**Comment by wangxidong06** [comment]
您好，这种情况是存在的，我们在进行分块截取时按照尽量按照完整语义单元进行截取(比如 一个大标题下的所有内容 或者 一个疾病的介绍 类似于这样的)，对于单个语义单元大于某一固定长度时(各种语言不等 一般为3584)，每3584个字符进行一次截断。再次感谢您的关注，有什么问题欢迎随时交流！
