### ISSUE TITLE
How to run the gguf model

### ISSUE THREAD

**Issue by BlackLotus** [FreedomIntelligence/Apollo#6]
Tried running the provided gguf files with llama.cpp and got
```
llama_model_load: error loading model: create_tensor: tensor 'blk.0.attn_q.weight' has wrong shape; expected  3072,  3072, got  3072,  4096,     1,     1
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/mnt/llama/gguf/Apollo-7B-q8_0.gguf'
main: error: unable to load model
```
Tried some other things as well (including converting the safetensors myself which resulted in the same problem)
It's probably something obvious that I'm forgetting here

**Comment by wangxidong06** [comment]
Hello, sorry for the delayed reply. I am not familiar with GGUF. I will debug it this weekend and try to solve it .

**Comment by wangxidong06** [comment]
You can try  following model first

7B: https://huggingface.co/mradermacher/Apollo-7B-GGUF
2B: https://huggingface.co/BoscoTheDog/Apollo_medical_gguf/tree/main

**Comment by BlackLotus** [comment]
At least the first one worked, didn't try the second one
