### ISSUE TITLE
Apollo的不同参数的模型prompt格式都是一样的吗？vllm推理好像不支持呢

### ISSUE THREAD

**Issue by chelovek21** [FreedomIntelligence/Apollo#9]
Apollo的不同参数的模型prompt格式是下面这样吗？
User:{query}\nAssistant:{response}<|endoftext|>

直接调用vllm推理，会报错：
File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/llama.py", line 337, in load_weights
    param = params_dict[name]
KeyError: 'model.layers.38.ln1.weight'

**Comment by wangxidong06** [comment]
你好 ,抱歉让您产生困惑，我们会在模型card中进行说明。

34B and 72B:
<|User|>:{query}\n<|Assistant|>:{response}<|endoftext|>
Others:
User:{query}\nAssistant:{response}<|endoftext|>

**Comment by wangxidong06** [comment]
关于推理错误，您在推理Apollo的哪一个模型呢？
Apollo-72b/34B vllm 推理请参考: https://github.com/FreedomIntelligence/Apollo/blob/main/src/evaluate/eval_72b_34b.py

**Comment by chelovek21** [comment]
谢谢
